#!/bin/bash

# Función para mostrar el banner
mostrar_banner() {
    echo -e "\e[1;31m"
    echo "************************************"
    echo "*          Xtrem-Tools             *"
    echo "************************************"
    echo -e "\e[0m"
}

# Función para mostrar el menú
mostrar_menu() {
    clear
    mostrar_banner
    echo "Elige la opción que quieres usar:"
    echo "1- Scan"
    echo "2- Hydra"
    echo "3- Recon"
    echo "4- Openvas"
    echo "5- Fuzzing"
    read -p "¿Cuál deseas usar? " opcion

    case $opcion in
        1) git clone https://github.com/Sr-Mxr/scan.git && /bin/bash scan/scan.sh ;;  
        2) git clone https://github.com/Sr-Mxr/BreakPass.git && /bin/bash BreakPass/hydra.sh ;;  
        3) git clone https://github.com/Sr-Mxr/recon.git && /bin/bash recon/recon.sh ;;  
        4) git clone https://github.com/Sr-Mxr/openvas.git && /bin/bash openvas/openvas.sh ;;  
        5) git clone https://github.com/Sr-Mxr/fuzzing.git && /bin/bash fuzzing/fuzzing.sh ;;  
        *) echo "Opción no válida";;
    esac
}

# Llamada a la función del menú
mostrar_menu

