#!/bin/bash

# Función para mostrar el banner
mostrar_banner() {
    echo -e "\e[1;31m"
    echo "************************************"
    echo "*          Xtrem-Tools             *"
    echo "************************************"
    echo -e "\e[0m"
}

# Función para mostrar el menú
mostrar_menu() {
    clear
    mostrar_banner
    echo "Elige la opción que quieres usar:"
    echo "1- Scan"
    echo "2- Hydra"
    echo "3- Recon"
    echo "4- Openvas"
    echo "5- KillWifi"
    echo "6- Fuzzing"
    read -p "¿Cuál deseas usar? " opcion

    case $opcion in
        1) git clone https://github.com/Sr-Mxr/scan.git ;;  
        2) git clone https://github.com/Sr-Mxr/BreakPass.git ;;  
        3) git clone https://github.com/Sr-Mxr/recon.git ;;  
        4) git clone https://github.com/Sr-Mxr/openvas.git ;;  
        5) git clone https://github.com/Sr-Mxr/kill_wifi.git ;; 
        6) git clone https://github.com/Sr-Mxr/fuzzing.git ;;  
        *) echo "Opción no válida";;
    esac
}

# Llamada a la función del menú
mostrar_menu
